### ISSUE TITLE
Time slider on USFS R&D Smoke Widget should be expanded by default

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#100]
The time slider on the USFS R&D Smoke Widget should be expanded by default, like it is for the NWS Smoke Widget.

**Comment by dwoodinnovate** [comment]
I was able to find a simple solution to make the R&D smoke widget stay expanded.

**Comment by dwoodinnovate** [comment]
This has been fixed and adam has approved the fix into production.
