### ISSUE TITLE
"Get Report" link in Summary Email sometimes doesn't resolve

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#102]
Three different users now have encountered a blank page when clicking on the Get Report link in the Wildfire Summary emails. They get a blank page and no report downloads. Clearing browser data reportedly doesn't help. The issue seems to have resolved itself for at least one of the original reporting users (will update issue after hearing back from the other). The R9 Spillphone operator is the latest to report the problem.

_Update: 2 out of 3 users who reported the issue are still encountering the problem. The issues apparently resolved itself for the original reporter._ 

For example, [this specific report link](https://r9data.response.epa.gov/download_latest.html?service_url=https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest/services/R9_Fire_Perimeter_Buffers/FeatureServer/0/query&feature_id=156#) was not working for the spillphone operator, but is working for me.

**Comment by tbock** [comment]
@aprins-innovate My guess is that layer wasn't added to the ER Cloud group.  It is now https://epa.maps.arcgis.com/home/item.html?id=34f62d591f1b49a287f7f78cfc60994d

Please have them try again and report back.

**Comment by aprins-innovate** [comment]
@tbock I reached out, will update issue when I hear back.

**Comment by aprins-innovate** [comment]
That seems to have fixed it, the spillphone operator confirms she successfully downloaded the report.
