### ISSUE TITLE
Modify Smoke Widgets alt text

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#105]
Modify the alt text for both Smoke Widget icons.

![image](https://user-images.githubusercontent.com/62261480/127399270-0ed57a8d-ce19-4ac2-84ed-14c00528bbf1.png)

On hover the left icon should say "BlueSky Smoke" and the right should say "National Weather Service Smoke"

**Comment by AliScott20** [comment]
both smoke widget icon alt texts have been updated to "BlueSky Smoke" and the right to "National Weather Service Smoke"
