### ISSUE TITLE
Toggling Fire Widget turns off some fire perimeters

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#112]
Some, not all, NIFC fire perimeters turn off when toggling on the Fire Widget.

https://user-images.githubusercontent.com/62261480/128377225-61dfc96d-4670-499a-ac55-a0e92354e9d1.mp4

**Comment by tbock** [comment]
Yeah its just clearing the filters on that layer when it exits.  I believe the original request was... if layer is already loaded leave it on... if it wasn't turn it off.  To be clear its not doing that right now but please confirm if so and will fix accordingly.

**Comment by aprins-innovate** [comment]
Yeah that's right. If a layer was already on when toggling the widget, leave it on.
