### ISSUE TITLE
Show POI based fires in fire widget

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-Widgets#114]
Since fires tied to POIs are tied to AGOL users we should be able to display an individuals POI based fires in the fire widget when they are logged into the COP.  Maybe a second section with another list?

**Comment by aprins-innovate** [comment]
Absolutely, this is a great idea. A second section called something like "My Fires" or "Fires Near My POI" would work.

**Comment by jdlandau123** [comment]
This has been implemented via the "My Fires" tab

**Comment by tbock** [comment]
Reopening for visibility

**Comment by jdlandau123** [comment]
Comments addressed
