### ISSUE TITLE
Add search bar to filter fires on-the-fly

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#117]
Add a search bar to the Fire Widget to allow user to filter fires on-the-fly.

**Comment by tbock** [comment]
@abprins should this be added to current and new widget?

**Comment by abprins** [comment]
@tbock I think it's more important that it gets added to the new widget at some point. I think we should put minimal effort into the current WAB widget if possible. Not a priority though, this hasn't come up in a while.
