### ISSUE TITLE
Deploy BlueSky Smoke Widget in COP

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#124]
Currently, only the National Weather Service Smoke Widget is deployed in the COP. We need to deploy the BlueSky Smoke Widget in the COP as well.

Configure the same as on the Fire Map:
![image](https://user-images.githubusercontent.com/62261480/132558985-e91714ba-e1be-4973-b914-42f7e883c17b.png)

**Comment by dwoodinnovate** [comment]
I have completed adding the blue Sky smoke widget to the R9 COP.
