### ISSUE TITLE
Rebuild and Combine Smoke and Wind Widgets in Experience Builder

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#129]
Currently, we have two different smoke widgets using different data. It'd be great if we could combine them into a single Experience Builder widget and allow the user to toggle between the data types, similar to how the Wind Widget is configured.

**Comment by tbock** [comment]
Also combining wind into this widget. @jdlandau123 @GeoFe33 what is the status of this issue.

**Comment by GeoFe33** [comment]
This widget is working well and as expected!


V/R,

*Lisa A. Jackson*

*GIS Developer/Analyst | Innovate! Inc.*

E: ***@***.***

Time Zone: Eastern

*Innovate! Inc. is a small, Hispanic and SBA-certified WOSB delivering
Geospatial, Salesforce, SharePoint, and Business Management Consulting
services. We are accessible via GSA Schedule 70, USACE IGI&S, and NITAAC
CIO-SP3 SB/8(a). Check us out at www.innovateteam.com
<http://www.innovateteam.com>.*
