### ISSUE TITLE
Designate Reviewer/Contact for Incorrect Tier II Facility Locations

### ISSUE THREAD

**Issue by krewritten** [USEPA/R9-Widgets#135]
We need to identify who will be the contact point for reviewing/editing incorrect locations in the Tier II facilities dataset. This information will be included in the rebuilt Tier II widget when users are viewing locations requiring review.

**Comment by abprins** [comment]
We'll check with Greg to see who he thinks this should be. Should it be limited to one person?

**Comment by krewritten** [comment]
Sounds great, I think one person is great but a few would work as long as there is some level of coordination on who is primarily responsible for it.

**Comment by tbock** [comment]
@abprins any word on this.  Perhaps its time to check in on TierII in general again?

**Comment by abprins** [comment]
@tbock no word on this specifically. I _finally_ heard back from the AZ Tier II support folks yesterday (you were cc'd) after two months of trying to pin them down, so yeah I think we're due a check-in after they get back to us with a solution. Until then, we're still stalled on updating our AZ data. I don't like meeting with Greg unless we have something concrete to show him, so let's hold until AZ is resolved?

**Comment by tbock** [comment]
@abprins anything to do here about designating a reviewer/contact for "incorrect" locations?
