### ISSUE TITLE
What is the RARNUM field in the ESI layers?

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-Widgets#14]
It is in most of the layers: https://r9.ercloud.org/epar9gis2/rest/services/R9GIS/HawaiiESI/MapServer/6

**Comment by dwoodinnovate** [comment]
@tbock From the metadata pdf here:
[METADATA.PDF](https://github.com/USEPA/R9-Widgets/files/1904576/METADATA.PDF)


![image](https://user-images.githubusercontent.com/11931923/38698016-7d25581c-3e48-11e8-9dc5-80f780563a6a.png)

**Comment by dwoodinnovate** [comment]
@tbock @dspinosa I updated the data model image

**Comment by dspinosa** [comment]
This model does not reflect what we see in the rest endpoint.  If time permits we can add support for sub relationships.
