### ISSUE TITLE
BlueSky Smoke Widget spatial offset

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#146]
Cheryl sent this screenshot to illustrate that she's still seeing a spatial offset in the BlueSky Smoke Widget.

![bluesky_smoke_widget_offset](https://user-images.githubusercontent.com/62261480/173409377-e84154b6-bf66-4ea4-a844-8a2a97255257.png)

**Comment by abprins** [comment]
@tbock, @jmaxmarno: Cheryl is still wondering about the BlueSky offset.

Here's what the data looks like in the production COP currently:
![image](https://user-images.githubusercontent.com/62261480/183488346-20a03824-b69a-40ad-afad-bfa79c606fe8.png)

and here's what the new time-enabled layer looks like:
![image](https://user-images.githubusercontent.com/62261480/183488430-a6b4b402-a94a-450c-9081-9cb745f967e6.png)

She also commented that it looks very different from the NWS data (below), I'm assuming that's because it's a different forecast model? Should they look the same?
![image](https://user-images.githubusercontent.com/62261480/183488868-3de88b3f-cab7-46c8-a1ab-8762eab1f563.png)


Is fixing the widget a bit lift? Should we maybe just switch the production COP over to using the new layer instead of updating the widget?

**Comment by tbock** [comment]
I think the most obvious choice is switching COP over to the new smoke service.  Appears stable now and should be a standard time enabled service now.

**Comment by tbock** [comment]
@jlherring fyi

**Comment by tbock** [comment]
WAB COP is being retired.
