### ISSUE TITLE
Fire Widget showing some 100% contained fires

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#148]
When toggling on the "Show R9 Fires > 5 Acres" setting, the Caldor fire and Tunnel fire show up in the widget, even though they're both 100% contained. Caldor is from last season.

Only current incidents should be visible in the widget interface.

![image](https://user-images.githubusercontent.com/62261480/173435130-91bb9d4d-9bab-456e-804c-5ff34e8014e5.png)

**Comment by jmaxmarno** [comment]
@abprins I'll make the change to filter out contained fires here, but fyi they are showing up here because they're still in the Current Incidents layer.

**Comment by abprins** [comment]
@jmaxmarno oh I see...well that's a pain. Can you think of any reason why they're maintaining a 100% contained fire from last season in the current Current Incidents layer? A fluke?

**Comment by jmaxmarno** [comment]
@abprins perhaps ongoing mitigation/maintenance? 
it's curious that they are still updating the 'current as of' date
![image](https://user-images.githubusercontent.com/9143887/173452695-9a9045f8-66da-41b4-b25e-4713a1e979c0.png)

**Comment by jmaxmarno** [comment]
@abprins closing this per our discussion. these unique cases will remain.
