### ISSUE TITLE
Wind EB Widget Issues & Improvements

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-Widgets#153]
- [ ] Need a way to toggle between forecast models without switching to the layer list
- [ ] Need a toggle to turn off the wind visualization
- [x] Review symbology? May need to make it more obvious on the light basemap (Make the wind visualizations more prominent and faster)

**Comment by GeoFe33** [comment]
- [ ] Do these layers need replaced?  They do not load in the web map for the EB COP.  @tbock 

![image](https://user-images.githubusercontent.com/54416878/184667829-8442ed60-fbb9-4c47-a860-0debc02ad12b.png)
![image](https://user-images.githubusercontent.com/54416878/184667975-258a2872-eb1b-4204-be9b-2555b4b0afb9.png)

**Comment by tbock** [comment]
"Review symbology? May need to make it more obvious on the light basemap (Make the wind visualizations more prominent and faster)"... this is configured at the web map level. Not an issue with any widgets.

**Comment by GeoFe33** [comment]
Need to fix the layers as they appear with errors (see images above) to make any visualization adjustments.

**Comment by tbock** [comment]
Will this widget be deployed in a view or will we try to put it in a widget controller or similar.  Asking b/c I presume we want to allow people to see this data with fire data. So users opens fire widget and then click wind/smoke widget and those layers are loaded with a new window opening to allow selection of wind model?

**Comment by GeoFe33** [comment]
The wind widget is deployed as a view (activated by a button).   Right now, widget controllers are not planned for this version of the EB COP.   Is there a way to add an option to turn on the wind layers while the fire widget is activated?

Last week, I swapped out the time-enabled wind layers and they worked in the map.  Now, I turn them on in the layer list and they are not working at all in the EB COP Response map (much less activated with the wind widget).

**Comment by GeoFe33** [comment]
- [ ] @tbock Are the wind forecast layers (GFS, HRRR, NAM) all working as expected?

**Comment by tbock** [comment]
"Is there a way to add an option to turn on the wind layers while the fire widget is activated?"  Anything is possible.  However specifically how should this work for the end user? Is there a button how does that button work? What happens when you switch to and away from that view?  But what you are more or less suggesting is that every single other widget will turn things on/off on open/close except this one?

**Comment by GeoFe33** [comment]
> "Is there a way to add an option to turn on the wind layers while the fire widget is activated?" Anything is possible. However specifically how should this work for the end user? Is there a button how does that button work? What happens when you switch to and away from that view? But what you are more or less suggesting is that every single other widget will turn things on/off on open/close except this one?

The wind/smoke widget should work as all the other widgets do.   Button activated - turn on pane in view and layers in the map.  Switch away or press button again, widget (pane in view) will deactivate and layers will turn off.

**Comment by tbock** [comment]
@jdlandau123 can you update this issue as needed?

**Comment by jdlandau123** [comment]
@GeoFe33 This one should also be good now but please let me know if we need to reopen
