### ISSUE TITLE
Fire Widget EB Issues

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-Widgets#154]
- [x] Turning on the fire widget should turn on the Current Incidents layer filtered to the fires in the widget
- [x] R9Notifiable layer adds multiple times to EB COP and Remedial. (Refresh does reset it, but it cascades)
- [ ] #161

**Comment by tbock** [comment]
I believe both issues for adding/removing and turning on/off layers have been resolved.  Please verify @GeoFe33

**Comment by GeoFe33** [comment]
These are resolved.  Checked the items above.

**Comment by GeoFe33** [comment]
- [ ] Updated cards with statistics that match with Fire Widget.  

Two services feed the Fire Widget and the associated cards in the EB.
	Ø 5 Acres - IRWIN [service](https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/USA_Wildfires_v1/FeatureServer/0)
10 Acres - R9 Notifiable [service](https://services.arcgis.com/cJ9YHowT8TU7DUyn/arcgis/rest/services/R9Notifiable/FeatureServer/0)

**Comment by GeoFe33** [comment]
- [ ] Individual fire list not showing in EB Fire Widget

![image](https://user-images.githubusercontent.com/54416878/190189407-c8ae3fe2-1d6a-4395-9bf6-c354de2e3fac.png)

**Comment by tbock** [comment]
Moving this to new issue and closing this issue
