### ISSUE TITLE
SDWIS Widget EB Issues

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-Widgets#155]
- [x] Clicking on a point freezes the map pane
- [x] SDWIS layers should not remain in the Layer List once the widget is not active or the focus of the EB

**Comment by GeoFe33** [comment]
![image](https://user-images.githubusercontent.com/54416878/182638834-7c96208a-598f-475b-a28a-d37aaac8a670.png)
Error present in staging

**Comment by tbock** [comment]
@GeoFe33 can you confirm the above issues are resolved?

**Comment by tbock** [comment]
from @GeoFe33 
- [ ] heading text needs to be a bit smaller

**Comment by GeoFe33** [comment]
- [ ] Please adjust COP to consume this service (for R9 and R1):  https://gis.r09.epa.gov/portal/home/item.html?id=944ccdfe8b4341d683fb99d82a5fdbb5

This service is considered deprecated and needs to be deleted from the R9 Portal: https://gis.r09.epa.gov/portal/home/item.html?id=183ebeb9bde84a34abe3b431d69f3c9c
***Please let me know when this change is made so I can officially delete this service.***

FYI, the National version of the SDWIS service is available on the R9 Portal: https://gis.r09.epa.gov/portal/home/item.html?id=cc5546eb12534555aacbcec14a7bf011

**Comment by tbock** [comment]
Ok we will make the service URL configurable probably

**Comment by GeoFe33** [comment]
Very, very slow loading on EPA Intranet.

**Comment by GeoFe33** [comment]
- [ ] "No Facilities found at this location" persists with list present.
![image](https://user-images.githubusercontent.com/54416878/183929905-4a40d885-83d5-41ae-9b32-0da14a53357a.png)

- [ ] Selector persists clicking an area that do not have facilities.
![image](https://user-images.githubusercontent.com/54416878/183931736-31bba588-119f-496e-a8e3-475235237d65.png)

**Comment by tbock** [comment]
Please verify the message issues above are resolved. 

Regarding performance issues I did find a couple of issues causing some queries to run over and over.  They are resolved but I dont know if there will be that much noticeable change.  Beyond that we would have to do more research. 

The layers should be removed/added on widget close/open now. 

Still haven't replicated freezing... unless it was the same as the issue about repeated queries I mentioned above. 

Please check off what is complete.

**Comment by GeoFe33** [comment]
> Please verify the message in the previous post are resolved.
> 
> 
> Please check off what is complete.

I've checked off what I can tell is complete.

**Comment by GeoFe33** [comment]
- [ ] (from Adam) also, the staging app is extremely slow for me now, I think I "caught up" to you, and things are taking ages to load. i took a quick look at the console and notices a TON of errors, so this may be contributing to the performance issues

![image](https://user-images.githubusercontent.com/54416878/184655763-eb57a5ca-78f4-4be6-a05e-bec4bac88b51.png)

**Comment by GeoFe33** [comment]
- [ ] New error for Staging (from Adam)
![image](https://user-images.githubusercontent.com/54416878/184655960-5e1c5b5e-a396-4aa8-a111-50bf1c09a8ad.png)

**Comment by GeoFe33** [comment]
- [ ] Both of us cannot see the SDWIS Widget on the Intranet

![image](https://user-images.githubusercontent.com/54416878/184656087-9bb6a676-48eb-4609-ad48-1a825a96dda1.png)

**Comment by tbock** [comment]
issues with not reaching services were b/c arc server was down 

"This may NOT be related to any widget, but does need to be addressed for the benefit of the App on the Intranet"  Fine but shoving that into the sdwis issue isn't the best place for that.  Create an issue if you think its necessary. 

This is still unchecked... is that correct? "No Facilities found at this location" persists with list present.

I am unable to replicate "Facility points appear AFTER clicking the map first." can you provide more details.

I have changed to smaller text size is this still an issue? " heading text needs to be a bit smaller"

**Comment by GeoFe33** [comment]
issues with not reaching services were b/c arc server was down - Okay.

"This may NOT be related to any widget, but does need to be addressed for the benefit of the App on the Intranet" Fine but shoving that into the sdwis issue isn't the best place for that. Create an issue if you think its necessary.  - _Asked about that yesterday, new issue has been create and applicable comments are added to that issue._

This is still unchecked... is that correct? "No Facilities found at this location" persists with list present.  _-That is now checked.  That message seemed to disappear yesterday._

I am unable to replicate "Facility points appear AFTER clicking the map first." can you provide more details.  _- Points take a long time to load, but they do load without clicking the map.  Has the service been updated?  The one being used does not have the correct domains in place.  _

_I_ have changed to smaller text size is this still an issue? " heading text needs to be a bit smaller"  _- This has been checked and resolved.  _

**Comment by tbock** [comment]
Service has been updated to this service: https://gis.r09.epa.gov/portal/home/item.html?id=944ccdfe8b4341d683fb99d82a5fdbb5

@GeoFe33 please verify it looks correct.

**Comment by GeoFe33** [comment]
@tbock  This looks correct!

**Comment by GeoFe33** [comment]
Number of features should be 78k.  This will also fix the domain issue that is still present for the pws_warehouse domain.  https://gis.r09.epa.gov/portal/home/item.html?id=944ccdfe8b4341d683fb99d82a5fdbb5

Picture: Shows incorrect number of facilities.
![image](https://user-images.githubusercontent.com/54416878/187252252-c20573cc-25e0-4815-b0bb-105cca15a04e.png)
This image (from the widget) matches the service that needs to be deleted.
Picture: showing incorrect service.
![image](https://user-images.githubusercontent.com/54416878/187252858-0cccbbe5-2237-44c8-9d0b-5258741de82b.png)

**Comment by tbock** [comment]
Not sure how that update didn't make it into the repo but the service is correct now I believe. Showing 78468

**Comment by tbock** [comment]
![image](https://user-images.githubusercontent.com/4040295/187483756-bbd23811-ecb6-454d-a36b-d7da2c5ed1b8.png)

The url you provided doesn't get updated automatically... you have to update that one like every other time.

**Comment by GeoFe33** [comment]
The app has been redeployed and the numbers are lining up.  Thank you.

**Comment by tbock** [comment]
@GeoFe33 can this issue be closed?

**Comment by GeoFe33** [comment]
Yes.
