### ISSUE TITLE
NRC Widget EB Issues

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-Widgets#158]
- [x] Change the list from dark theme to light

**Comment by tbock** [comment]
pushed change but can't test b/c there is only one web eoc point at this moment.  

@GeoFe33 please confirm

**Comment by GeoFe33** [comment]
I've removed the filter on the WebEOC layer for testing purposes.  

- [ ] Unable to see list when selecting a point.
- [ ] When list appears and a site is selected from the list, the report does not appear.

- [ ]

**Comment by GeoFe33** [comment]
- [ ] Perhaps add "Zoom in to see points." or something similar.  The points do not immediately appear when the NRC Widget is activated.

**Comment by tbock** [comment]
Moved last comment to new issue and closing this issue.

**Comment by GeoFe33** [comment]
- [ ] WebEOC layer needs to turn off when user is moves to another widget or the Layers pane.  Right now, it will not turn off after the NRC Widget is turned on.
