### ISSUE TITLE
EB COP Performance Issues

### ISSUE THREAD

**Issue by GeoFe33** [USEPA/R9-Widgets#159]
- [x]  Very, very slow loading on EPA Intranet. ((This may be a specific issue for my VDI Pro. Adam said he's been able to work with it. Loading and interacting with the EB COP Staging is very slow for me.))

Regarding performance issues I did find a couple of issues causing some queries to run over and over. They are resolved but I don't know if there will be that much noticeable change. Beyond that we would have to do more research. (from Travis)

_[This may NOT be related to any widget, but does need to be addressed for the benefit of the App on the Intranet]_

- [x] (from Adam) also, the staging app is extremely slow for me now, I think I "caught up" to you, and things are taking ages to load. i took a quick look at the console and notices a TON of errors, so this may be contributing to the performance issues

![image](https://user-images.githubusercontent.com/54416878/184655763-eb57a5ca-78f4-4be6-a05e-bec4bac88b51.png)

**Comment by GeoFe33** [comment]
Stripped down app with EB COP Web Map (no widgets) available here: https://r9data.response.epa.gov/apps/EBCOPStagingTest/

Token needs work.  I was able to access by signing with the EB COP (https://r9data.response.epa.gov/apps/EBCOPStaging/) first.

**Comment by GeoFe33** [comment]
Edge errors:
![image](https://user-images.githubusercontent.com/54416878/184900531-efc4c9c4-7139-4151-9c65-d1278479299b.png)

**Comment by GeoFe33** [comment]
- [ ] Permissions issues for layers ([link](https://github.com/USEPA/R9-Widgets/issues/153#issuecomment-1215194999))

![image](https://user-images.githubusercontent.com/54416878/184904565-68d392bf-c666-4524-8023-17e2f9340fd7.png)

**Comment by GeoFe33** [comment]
- [ ] EB with widgets and an empty web map Staging for [](https://r9data.response.epa.gov/apps/EBCOPStagingTest/)

**Comment by GeoFe33** [comment]
Ticket submitted for EB performance issues

**Comment by tbock** [comment]
@GeoFe33 any status on this?

**Comment by tbock** [comment]
@GeoFe33 any status on this?

**Comment by GeoFe33** [comment]
Spoke with GeoServices and worked with them on several issues.  As of this
point, they do not see the concern or slow-downs that we see.

V/R,

*Lisa A. Jackson*

*GIS Developer/Analyst | Innovate! Inc.*

E: ***@***.***

Time Zone: Eastern

*Innovate! Inc. is a small, Hispanic and SBA-certified WOSB delivering
Geospatial, Salesforce, SharePoint, and Business Management Consulting
services. We are accessible via GSA Schedule 70, USACE IGI&S, and NITAAC
CIO-SP3 SB/8(a). Check us out at www.innovateteam.com
<http://www.innovateteam.com>.*
