### ISSUE TITLE
Time Slider widget UI improvements

### ISSUE THREAD

**Issue by jdlandau123** [USEPA/R9-Widgets#166]
- [ ] Lock in widget position for multiple screen sizes
- [x] Change wind model selector to toggles
- [ ] Separate from widget controller?

**Comment by GeoFe33** [comment]
- [ ] Change icon to something more intuitive for the time slider

**Comment by GeoFe33** [comment]
Update on the position issues - I have found a "happy medium" on placement.  I'll keep observing the behavior.

**Comment by jdlandau123** [comment]
@GeoFe33 These items have been addressed, please let me know if any additional changes are needed and we can reopen
