### ISSUE TITLE
My Fires Improvements

### ISSUE THREAD

**Issue by jdlandau123** [USEPA/R9-Widgets#175]
- [x] Only show POIs that are subscribed to
- [x] If multiple POIs are associated with the same fire, it should only appear in the list once
- [ ] ~~Implement a method of deleting "orphan" POIs (points that are not subscribed to)~~

**Comment by abprins** [comment]
We have some clarity from CH after showing this to her.

- [ ] rename the tab to "My Notifications"
- [ ] move "Associated POI" line above the fire name

Also, she doesn't want us to delete orphaned POIs. She thinks people will want to reuse them. So we'll need to figure out a solution to delete unnecessary POIs (like all my test points), but keep relevant ones.

**Comment by jdlandau123** [comment]
Also adding improvements to filtering

- [ ] If My Fires tab is active and >5 acres toggle is off, filter fires on map to match list
