### ISSUE TITLE
Wind/Smoke Widget: animate by wind speed?

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#186]
Cheryl wants to know if it's possible to animate or symbolize the wind layer pixels variably based on their actual wind speed.

**Comment by tbock** [comment]
@abprins The animation is all now using out of the box functionality.  Just no one has bothered to try out different styling options.  It looks to me that you can do what you are asking by switching them to a color ramp under styling options for the layer in the web map. 
![image](https://user-images.githubusercontent.com/4040295/223762441-20fd6595-6fd1-4412-8846-4c45385edeee.png)

**Comment by abprins** [comment]
@tbock that's great, thanks. I'll play around with it.
