### ISSUE TITLE
Wind/Smoke Widget: legend symbology

### ISSUE THREAD

**Issue by abprins** [USEPA/R9-Widgets#188]
The legend for the smoke data just shows RGB, possible to show the actual legend?

![image](https://user-images.githubusercontent.com/62261480/223522132-5efc85f2-be09-4079-a108-95a4f0759e38.png)

**Comment by jdlandau123** [comment]
These are the changes that need to be made to the web map. I don't have permissions to save changes to the COP map so leaving this here for @abprins and @GeoFe33 

![image](https://user-images.githubusercontent.com/46530995/225721085-0dd6c45b-3b56-44f0-a4fa-00a6de0381d4.png)
