### ISSUE TITLE
Expand Wind Widget data sources

### ISSUE THREAD

**Issue by tbock** [USEPA/R9-Widgets#23]
Thanks again for taking time to help me understand your application.

 

There are several factors that are likely to be important to providing accurate information to your users:

 

Domain covered—are data available for the area of interest?
Resolution of the computational grid (or its equivalent—GFS doesn’t use a grid)—This will affect how well a model can resolve details of the topography. Greater detail can be important in areas where elevations change rapidly (e.g., mountains) or where there are land-water boundaries. Representing that detail can be important as terrain and land-water boundaries can significantly affect winds.
The frequency of the simulation—Every model will provide data for each hour, but some models are rerun every hour while others may only be rerun every 6. The longer the period between runs of a model, the greater the opportunity for actual conditions to deviate from the conditions predicted by the model.
Accuracy of wind predictions in the area of interest—Each model has strengths and weaknesses and these can vary by region. Someone with expertise in using wind predictions in your region might be able to tell you which models do the best.
 

Here are some data sets that you might want to consider. My descriptions are generally based on information on the web pages, which may not be current.

 

High Resolution Rapid Refresh (HRRR) Model

 

Domain: Operational runs cover the CONUS. There are experimental predictions for Hawaii.

Resolution: 3km

Frequency of simulation: Hourly

 

Visualizations

Data files

 

North American Model (NAM)

 

Domain: CONUS, Hawaii, and Guam

Resolution: 3km

Frequency of simulation: Every 6 hours

 

During the fire season, a 1.5km resolution model is run with the domain chosen by the National Interagency Fire Center.

 

Visualizations

Descriptions of data files

Data files

 

I’d also suggest talking to one or more of the people involved in the fire response who work with wind data to understand which wind data sets they find most useful. Each model/analysis has different strengths/weaknesses.

**Comment by tbock** [comment]
After some investigate we figured out we can get the data and process it but requires a little bit of change  in the JavaScript on top of the changes to the UI to be able to switch to different models. 

Changes have been tested for NAM and HRRR in JS are available here: https://github.com/USEPA/R9-Widgets/tree/multiple_wind_models_support

Additional processing of HRRR and NAM GRIB2 files is required. 
reproject using python gdal: 
`from osgeo.gdal import  Warp
Warp('.\\Wind\\hrrr.reprojected.grib2', '.\\Wind\\hrrr.original.grib2', dstSRS='WGS84')`

translate back to correct DATA_ENCODING
`from osgeo.gdal import  Translate
Translate('.\\Wind\\nam.test4.grib2', '.\\Wind\\nam.warp.grib2', options='-co DATA_ENCODING=SIMPLE_PACKING')`

run same grib2json command as currently being used in: https://github.com/USEPA/R9-Python/blob/master/Wind/process_grib_files.py

**Comment by tbock** [comment]
Warp in action
![image](https://user-images.githubusercontent.com/4040295/100283753-e5755e80-2f22-11eb-92ed-bc7eb8112447.png)

**Comment by aprins-innovate** [comment]
Closing this because we've included HRRR and NAM in the new Wind Widget.
