### ISSUE TITLE
Create Sadie Widget

### ISSUE THREAD

**Issue by dspinosa** [USEPA/R9-Widgets#24]
Backend would be django, front-end WAB widget
Start FY 2020?
Scribe is the primary db repo'd source for sampled data.  Need to determine if there is a map service to hit, or create an API with django
Look at geojson
https://github.com/Esri/geojson-layer-js

https://r9.ercloud.org/Sadie/

**Comment by dspinosa** [comment]
![image](https://user-images.githubusercontent.com/5093530/59305436-1e4a4680-8c4f-11e9-91e5-c55b4ccf5f69.png)

**Comment by dspinosa** [comment]
![image](https://user-images.githubusercontent.com/5093530/59305837-ded02a00-8c4f-11e9-911f-888bc8af04a3.png)

**Comment by froberts** [comment]
Per a comment from Cheryl on this work: We are looking for SADIE to be incorporated into our Superfund DMT and we want to develop a SCRIBE Widget.

**Comment by froberts** [comment]
As a sample data set to test SADIE use this: First go to this website:
https://r9.ercloud.org/Sadie/
 
 
Then:
Pick the picklist to: RAES-TO001 - Northern Agency Tronox Mines
Put in the Password from below: proj3553

**Comment by dspinosa** [comment]
https://github.com/USEPA/R9-NAUM/issues/79

**Comment by tbock** [comment]
We have created the new Scribe data viewer tool. This allows creating host feature service per project.  Perhaps this widget should show a list of host services created by the scribe tool and allow adding those to the map as well as enabling some additional data exploration of the services.  

@jlherring @abprins assuming this isn't super high on the list and should only be done in EB?

**Comment by abprins** [comment]
I think that's a safe assumption @tbock, I feel like we should minimize the amount of new stuff we do in WAB.

**Comment by jlherring** [comment]
haven't heard any talk of it since we updated the layers and did scribe explorer, def closeout and can revisit if it comes up again
