### ISSUE TITLE
Wind Widget - Integrate map Zoom Scale into VELOCITY_SCALE

### ISSUE THREAD

**Issue by dwoodinnovate** [USEPA/R9-Widgets#28]
For the use case of the Central Metals WAB, the wind widget blows out the screen when zoomed into the map this close. https://r9.ercloud.org/R9WAB/centralmetal/

On testing, if the VELOCITY_SCALE is set to 0.00005 it looks nice. The default is 0.005.

I propose adding functionality to update the VELOCITY_SCALE value in relation to the map zoom scale.

![windWidget](https://user-images.githubusercontent.com/11931923/76442588-659c6980-637e-11ea-9d67-f3874a80b43f.png)

**Comment by tbock** [comment]
New widget uses Esri flow renderer so will not be using this library in the future anyways.
