### ISSUE TITLE
Smoke Widget: correct geographic offset

### ISSUE THREAD

**Issue by rhomsher** [USEPA/R9-Widgets#35]
There seems to be a major geographic offset in the smoke widget data (smoke is appearing far to the west of where it should be). 

Hopefully the date for the data is correct now, but may want to double check.

**Comment by tbock** [comment]
Can you double check that and include a screenshot if still appears wrong.  I'm not seeing it.

**Comment by rhomsher** [comment]
Okay, clarification: it appears to be fine in the [original COP (i.e. V8.3-E)](https://r9.ercloud.org/R9WAB/R9COP/) but not in the new [COP V2.0](https://r9.ercloud.org/R9WAB/R9COPtabbed/#). I also have the widget in the [R9 Current Smoke and Air Quality Map V1.0](https://r9.ercloud.org/R9WAB/R9SmokeMap/), which is behaving like COP V2.0.

**Comment by rhomsher** [comment]
Question: why are we using the CA/NV 1.33-km vs. the Southwest 4-km, which also covers AZ? Just resolution? Don't remember.

**Comment by tbock** [comment]
On the question of why which data set. Its possible southwest didn't exist at the time or we just went with this one b/c of resolution like you say. 

Widget in the COP V2.0 is old and needs to be replaced.  Assigning issue to @dwoodinnovate .

**Comment by rhomsher** [comment]
@dwoodinnovate  please also update the widget in the [R9 Current Smoke and Air Quality Map V1.0](https://r9.ercloud.org/R9WAB/R9SmokeMap/)

**Comment by dwoodinnovate** [comment]
@rhomsher COP V2.0 smoke widget updated

**Comment by dwoodinnovate** [comment]
@rhomsher updated the R9 Current Smoke and Air Quality Map. The smoke widget looks to be working correctly and I updated the version to V1.2
