### ISSUE TITLE
Add counties under the Fire (incident name) 

### ISSUE THREAD

**Issue by David-Yarnell** [USEPA/R9-Widgets#41]
Add counties under the Fire (incident name). If available in the feature layer.

**Comment by tbock** [comment]
Not currently available but certainly can be.

**Comment by David-Yarnell** [comment]
This data is not in the feature layer. May be something we want to add down the road.

**Comment by tbock** [comment]
https://user-images.githubusercontent.com/4040295/109363807-440fe880-7842-11eb-8df8-df94383b21f5.png
