### ISSUE TITLE
Replace "Get Report" and "Zoom To" links with icons

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#57]
Replace "Get Report" and "Zoom To" links with icons like the ones attached (doesn't have to be these exact icons, just something along these lines). This should clean up the interface a bit more and will prevent all the ugly blue and purple text.

![report_icon](https://user-images.githubusercontent.com/62261480/97360201-19456180-185b-11eb-905a-fba0ba092a64.png)
![zoom_icon](https://user-images.githubusercontent.com/62261480/97359562-29a90c80-185a-11eb-9c70-b454b76f6598.png)

**Comment by aprins-innovate** [comment]
Whoa those are huge, sorry.

**Comment by David-Yarnell** [comment]
@aprins-innovate this is complete and ready for your testing and deployment
