### ISSUE TITLE
Add alt text to Report and Zoom icons

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#61]
Add alt text to new icons: "Get Report" & "Zoom To"

**Comment by tbock** [comment]
![image](https://user-images.githubusercontent.com/4040295/109363807-440fe880-7842-11eb-8df8-df94383b21f5.png)
![image](https://user-images.githubusercontent.com/4040295/109363829-4f631400-7842-11eb-867e-c2c411c82d67.png)
