### ISSUE TITLE
Replace Zoom and Report icons

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#63]
CH asked that we tweak the Zoom and Report icons to be a little clearer. Specifically, add a plus sign inside the magnifying glass and change the report icon to look more like a document (no check mark).

Examples:
![zoom_icon](https://user-images.githubusercontent.com/62261480/100901077-53b4a680-3478-11eb-9973-abe009ffc99f.png) ![report_icon](https://user-images.githubusercontent.com/62261480/100901172-6929d080-3478-11eb-802a-dc94531bbd85.png)

**Comment by David-Yarnell** [comment]
@aprins-innovate we can use the icons that you have attached to this issue but the hover over functionality with the current icon will not apply to the new. Essentially the hover over functionality is just switching to another icon that is darker and stands out a bit more.

**Comment by aprins-innovate** [comment]
I just threw together these lighter icons, can we retain the hover behavior with these?

![zoom_icon](https://user-images.githubusercontent.com/62261480/101660872-815f9980-39fc-11eb-8a73-216888ca93dc.png)![zoom_icon_hover](https://user-images.githubusercontent.com/62261480/101660231-cafbb480-39fb-11eb-8597-1b2084dd9dc5.png)
![report_icon](https://user-images.githubusercontent.com/62261480/101660186-bc150200-39fb-11eb-8ae5-cf5f46fe01a1.png)![report_icon_hover](https://user-images.githubusercontent.com/62261480/101660192-be775c00-39fb-11eb-9127-0b50d32840b9.png)

**Comment by David-Yarnell** [comment]
@aprins-innovate yes that should work. Thanks.
