### ISSUE TITLE
Call out # of RMP, NPL, and Tribes

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#64]
CH asked that we call out the number of RMP sites, NPL sites, and Tribes affected by each fire in the widget. We'll probably need to enlarge each fire's section a bit to fit this.

**Comment by tbock** [comment]
@aprins-innovate assuming this is for the 10 mile buffer just like the emails

**Comment by aprins-innovate** [comment]
@tbock correct.

**Comment by tbock** [comment]
@aprins-innovate hows this? 
![image](https://user-images.githubusercontent.com/4040295/109363544-b59b6700-7841-11eb-9acc-884ef452bfa1.png)
side note... how are you going to demo this?

**Comment by aprins-innovate** [comment]
@tbock this looks good to me.

For demos we'll have to use screenshots for the time being. Might be worth thinking about setting up a dummy dataset for this type of seasonal data.
