### ISSUE TITLE
Change blues in widget

### ISSUE THREAD

**Issue by jlherring** [USEPA/R9-Widgets#74]
Per convo in Slack - thinking the new blues in the sdwis widget are too similar. need to either be farther apart or exactly the same. now they're just close enough to wonder and not be sure if that info is related:

![image](https://user-images.githubusercontent.com/17882165/105075732-25a31a00-5a58-11eb-9ea9-cf248377b0b0.png)

Thinking maybe we need to diverge from blue. Also open to putting white text on a darker background, if needed. Thoughts on going purple? 
![image](https://user-images.githubusercontent.com/17882165/105076756-7e26e700-5a59-11eb-8fab-567897edade6.png)

**Comment by GeoFe33** [comment]
Attended the meeting this morning.  The feedback was to remove all color and lean towards cohesive formatting (using the lines and centered headings).

**Comment by GeoFe33** [comment]
Move the sections around according to relevance.

![Screenshot 2021-01-20 154725](https://user-images.githubusercontent.com/54416878/105232762-db449a80-5b36-11eb-936b-ba2db3704021.png)

**Comment by GeoFe33** [comment]
This version was accepted by product owners on 1/22/2021 during the SDWIS Check-In call.

**Comment by tbock** [comment]
Issue closed per comment above.
