### ISSUE TITLE
Replace WebEOC Reports widget icon

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#77]
Somehow the widget icon reverted back to the original one.

Here's the right one:
![WebEOC_Widget_Icon](https://user-images.githubusercontent.com/62261480/106913387-ca5c6300-66b8-11eb-89ce-3ebc19ac1967.png)

**Comment by tbock** [comment]
added icon to repo and confirmed it landed in COP repo correctly.
