### ISSUE TITLE
Integrate the new fire widget OnOpen/OnClose layer handling to other widgets

### ISSUE THREAD

**Issue by dwoodinnovate** [USEPA/R9-Widgets#83]
Desired Feature:
The new functionality added to the Fire widget's OnOpen/OnClose layer handling that enables widget specific layers when the widget opens then disables them when closed, but if the layer was enabled before the widget was opened widget does not disable that layer OnClose.

This is a very desirable feature for the other custom widgets. Here is a list of widgets that would benefit from the addition of this OnOpen/OnClose layer handling feature.

- [x] Tier II Identify Widget
- [x] RMP Identify Widget
- [x] Smoke Widget
- [x] Wind Widget
- [x] SDWIS Widget
- [ ] ~~GRP Widget~~
- [ ] ~~ESI Widget~~

**Comment by tbock** [comment]
Confused about this issue... this functionality was already baked into SDWIS and RMP unless there are specific issues with them.  Wind has always done unless there are additional layers that are desired to be toggled.  Same for smoke. ESI is likely not going to be used and GRP is in a similar boat.   Tier II is the only widget I know of needing this.  

@aprins-innovate @dwoodinnovate Let me know what I'm missing here.

**Comment by aprins-innovate** [comment]
That's right, since ESI and GRP are out, it's just Tier II that needs it.

**Comment by abprins** [comment]
@tbock Bumping this issue because Lisa and I are presenting COP Experience Builder rebuild progress, and this functionality for the Tier II widget is pretty important. Folks who use Tier II data are not really willing to toggle the data layer on before toggling the widget.
