### ISSUE TITLE
Change Fire Widget buffer color

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#88]
- [x] Change fill and outline color to white 
- [x] Increase thickness of buffer outline slightly (1.5pt? 2pt?)
- [x] Decrease transparency of fill (75%?)

**Comment by jmaxmarno** [comment]
![image](https://user-images.githubusercontent.com/9143887/128901179-245e273e-0b1e-4115-966a-bd6b0422c1eb.png)
@aprins-innovate - Can be tweaked by saving the layer symbology here:
https://epa.maps.arcgis.com/home/item.html?id=b76b8477849a40e3827f9c45d3bae783#visualize
