### ISSUE TITLE
Add info popups to smoke widgets

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#94]
Add popups for each smoke widget in the Fire Map, similar to the wind widget info popup.

**National Weather Service Smoke Forecast**
This widget provides a visualization of projected visible smoke across the contiguous United States for the next 48 hours in 1 hour increments. It is updated every 24 hours by the National Weather Service (NWS). Concentrations are reported in micrograms per cubic meter.

Disclaimer:
This data is provided for informational purposes and is not monitored 24/7 for accuracy and currency.

**US Forest Service Experimental Research Output: Smoke Predictions**
This widget provides a visualization of results from a wide array of daily smoke model prediction runs, particularly the BlueSky based smoke model runs done by USFS-AirFire.

Disclaimer:
This tool is provided for research purposes only, and may not accurately reflect what happened/will happen for a variety of reasons. Data are provisional and subject to change. Use at your own risk.

**Comment by dwoodinnovate** [comment]
The SmokeSlider Widget has been updated.

**Comment by dwoodinnovate** [comment]
The Smoke widget has been updated also.

**Comment by dwoodinnovate** [comment]
This fix has been completed and Adam approved the fix so it is live in the fire map
